// Los 42 municipios del departamento del Valle del Cauca, Colombia.
// Usado para sembrar la tabla Municipio (prisma/seed.ts) y, en el futuro,
// para poblar directamente el <select> del formulario de censo.
export const MUNICIPIOS_VALLE_DEL_CAUCA: string[] = [
  "Alcalá",
  "Andalucía",
  "Ansermanuevo",
  "Argelia",
  "Bolívar",
  "Buenaventura",
  "Buga",
  "Bugalagrande",
  "Caicedonia",
  "Cali",
  "Calima",
  "Candelaria",
  "Cartago",
  "Dagua",
  "El Águila",
  "El Cairo",
  "El Cerrito",
  "El Dovio",
  "Florida",
  "Ginebra",
  "Guacarí",
  "Jamundí",
  "La Cumbre",
  "La Unión",
  "La Victoria",
  "Obando",
  "Palmira",
  "Pradera",
  "Restrepo",
  "Riofrío",
  "Roldanillo",
  "San Pedro",
  "Sevilla",
  "Toro",
  "Trujillo",
  "Tuluá",
  "Ulloa",
  "Versalles",
  "Vijes",
  "Yotoco",
  "Yumbo",
  "Zarzal",
];
